export const MaleHairOverlays = {
    0: { collection: 'mpbeach_overlays', overlay: 'FM_Hair_Fuzz' },
    1: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_001' },
    2: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_002' },
    3: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_003' },
    4: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_004' },
    5: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_005' },
    6: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_006' },
    7: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_007' },
    8: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_008' },
    9: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_009' },
    10: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_013' },
    11: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_002' },
    12: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_011' },
    13: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_012' },
    14: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_014' },
    15: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_015' },
    16: { collection: 'multiplayer_overlays', overlay: 'NGBea_M_Hair_000' },
    17: { collection: 'multiplayer_overlays', overlay: 'NGBea_M_Hair_001' },
    18: { collection: 'multiplayer_overlays', overlay: 'NGBus_M_Hair_000' },
    19: { collection: 'multiplayer_overlays', overlay: 'NGBus_M_Hair_001' },
    20: { collection: 'multiplayer_overlays', overlay: 'NGHip_M_Hair_000' },
    21: { collection: 'multiplayer_overlays', overlay: 'NGHip_M_Hair_001' },
    22: { collection: 'multiplayer_overlays', overlay: 'NGInd_M_Hair_000' },
    24: { collection: 'mplowrider_overlays', overlay: 'LR_M_Hair_000' },
    25: { collection: 'mplowrider_overlays', overlay: 'LR_M_Hair_001' },
    26: { collection: 'mplowrider_overlays', overlay: 'LR_M_Hair_002' },
    27: { collection: 'mplowrider_overlays', overlay: 'LR_M_Hair_003' },
    28: { collection: 'mplowrider2_overlays', overlay: 'LR_M_Hair_004' },
    29: { collection: 'mplowrider2_overlays', overlay: 'LR_M_Hair_005' },
    30: { collection: 'mplowrider2_overlays', overlay: 'LR_M_Hair_006' },
    31: { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_000_M' },
    32: { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_001_M' },
    33: { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_002_M' },
    34: { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_003_M' },
    35: { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_004_M' },
    36: { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_005_M' },
    72: {
        collection: 'mpgunrunning_overlays',
        overlay: 'MP_Gunrunning_Hair_M_000_M'
    },
    73: {
        collection: 'mpgunrunning_overlays',
        overlay: 'MP_Gunrunning_Hair_M_001_M'
    }
};

export const FemaleHairOverlays = {
    0: { collection: 'mpbeach_overlays', overlay: 'FM_Hair_Fuzz' },
    1: { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_001' },
    2: { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_002' },
    3: { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_003' },
    4: { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_004' },
    5: { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_005' },
    6: { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_006' },
    7: { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_007' },
    8: { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_008' },
    9: { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_009' },
    10: { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_010' },
    11: { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_011' },
    12: { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_012' },
    13: { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_013' },
    14: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_014' },
    15: { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_015' },
    16: { collection: 'multiplayer_overlays', overlay: 'NGBea_F_Hair_000' },
    17: { collection: 'multiplayer_overlays', overlay: 'NGBea_F_Hair_001' },
    18: { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_007' },
    19: { collection: 'multiplayer_overlays', overlay: 'NGBus_F_Hair_000' },
    20: { collection: 'multiplayer_overlays', overlay: 'NGBus_F_Hair_001' },
    21: { collection: 'multiplayer_overlays', overlay: 'NGBea_F_Hair_001' },
    22: { collection: 'multiplayer_overlays', overlay: 'NGHip_F_Hair_000' },
    23: { collection: 'multiplayer_overlays', overlay: 'NGInd_F_Hair_000' },
    25: { collection: 'mplowrider_overlays', overlay: 'LR_F_Hair_000' },
    26: { collection: 'mplowrider_overlays', overlay: 'LR_F_Hair_001' },
    27: { collection: 'mplowrider_overlays', overlay: 'LR_F_Hair_002' },
    28: { collection: 'mplowrider2_overlays', overlay: 'LR_F_Hair_003' },
    29: { collection: 'mplowrider2_overlays', overlay: 'LR_F_Hair_003' },
    30: { collection: 'mplowrider2_overlays', overlay: 'LR_F_Hair_004' },
    31: { collection: 'mplowrider2_overlays', overlay: 'LR_F_Hair_006' },
    32: { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_000_F' },
    33: { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_001_F' },
    34: { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_002_F' },
    35: { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_003_F' },
    36: { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_003' },
    37: { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_006_F' },
    38: { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_004_F' },
    76: {
        collection: 'mpgunrunning_overlays',
        overlay: 'MP_Gunrunning_Hair_F_000_F'
    },
    77: {
        collection: 'mpgunrunning_overlays',
        overlay: 'MP_Gunrunning_Hair_F_001_F'
    }
};
